Repository adhambadawi/mini-survey-monkey, pull requests merged in 2024-11, with the labels that each got.

#34 Implemented Survey Closure, Reopening, and Deletion, relates to issues #10 #32 #33
  src/main/java/com/github/adhambadawi/minisurveymonkey/config/SecurityConfig.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/controller/WebController.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/service/SurveyService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/surveyClosed.html
Labels: feature, backend, frontend

#35 Fixed survey deletion bug, relates to issue #33 and #34
  src/main/java/com/github/adhambadawi/minisurveymonkey/model/Question.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/model/Survey.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/model/User.java
Labels: feature, backend

#39 Added frontend changes and integrated Bootstrap
  src/main/java/com/github/adhambadawi/minisurveymonkey/config/SecurityConfig.java
  src/main/resources/static/css/bootstrap-grid.css
  src/main/resources/static/css/bootstrap-grid.css.map
  src/main/resources/static/css/bootstrap-grid.min.css
  src/main/resources/static/css/bootstrap-grid.min.css.map
  src/main/resources/static/css/bootstrap-grid.rtl.css
  src/main/resources/static/css/bootstrap-grid.rtl.css.map
  src/main/resources/static/css/bootstrap-grid.rtl.min.css
  src/main/resources/static/css/bootstrap-grid.rtl.min.css.map
  src/main/resources/static/css/bootstrap-reboot.css
  src/main/resources/static/css/bootstrap-reboot.css.map
  src/main/resources/static/css/bootstrap-reboot.min.css
  src/main/resources/static/css/bootstrap-reboot.min.css.map
  src/main/resources/static/css/bootstrap-reboot.rtl.css
  src/main/resources/static/css/bootstrap-reboot.rtl.css.map
  src/main/resources/static/css/bootstrap-reboot.rtl.min.css
  src/main/resources/static/css/bootstrap-reboot.rtl.min.css.map
  src/main/resources/static/css/bootstrap-utilities.css
  src/main/resources/static/css/bootstrap-utilities.css.map
  src/main/resources/static/css/bootstrap-utilities.min.css
  src/main/resources/static/css/bootstrap-utilities.min.css.map
  src/main/resources/static/css/bootstrap-utilities.rtl.css
  src/main/resources/static/css/bootstrap-utilities.rtl.css.map
  src/main/resources/static/css/bootstrap-utilities.rtl.min.css
  src/main/resources/static/css/bootstrap-utilities.rtl.min.css.map
  src/main/resources/static/css/bootstrap.css
  src/main/resources/static/css/bootstrap.css.map
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/bootstrap.min.css.map
  src/main/resources/static/css/bootstrap.rtl.css
  src/main/resources/static/css/bootstrap.rtl.css.map
  src/main/resources/static/css/bootstrap.rtl.min.css
  src/main/resources/static/css/bootstrap.rtl.min.css.map
  src/main/resources/static/css/style.css
  src/main/resources/static/js/bootstrap.bundle.js
  src/main/resources/static/js/bootstrap.bundle.js.map
  src/main/resources/static/js/bootstrap.bundle.min.js
  src/main/resources/static/js/bootstrap.bundle.min.js.map
  src/main/resources/static/js/bootstrap.esm.js
  src/main/resources/static/js/bootstrap.esm.js.map
  src/main/resources/static/js/bootstrap.esm.min.js
  src/main/resources/static/js/bootstrap.esm.min.js.map
  src/main/resources/static/js/bootstrap.js
  src/main/resources/static/js/bootstrap.js.map
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/bootstrap.min.js.map
  src/main/resources/static/js/survey.js
  src/main/resources/static/public/survey.js
  src/main/resources/templates/fillSurvey.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/result.html
  src/main/resources/templates/surveyClosed.html
  src/main/resources/templates/surveyDetails.html
  src/main/resources/templates/surveyForm.html
Labels: frontend

#50 Fixed 2 bugs relates to issues #47 and #48
  src/main/java/com/github/adhambadawi/minisurveymonkey/config/SecurityConfig.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/controller/ResponseController.java
  src/main/resources/templates/fillSurvey.html
  src/test/java/com/github/adhambadawi/minisurveymonkey/ResponseControllerIntegrationTest.java
  src/test/java/com/github/adhambadawi/minisurveymonkey/SurveyControllerIntegrationTest.java
Labels: bug

#51 Implemented the Multiple Choice Question Feature relates to issue #43
  pom.xml
  src/main/java/com/github/adhambadawi/minisurveymonkey/controller/ResponseController.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/model/Question.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/model/Response.java
  src/main/java/com/github/adhambadawi/minisurveymonkey/service/QuestionService.java
  src/main/resources/static/js/survey.js
  src/main/resources/templates/fillSurvey.html
  src/main/resources/templates/result.html
  src/test/java/com/github/adhambadawi/minisurveymonkey/ResponseControllerIntegrationTest.java
Labels: feature, backend, frontend
